# Generated by Django 5.2.7 on 2025-10-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredapi',
            name='last_check',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monitoredapi',
            name='status',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
    ]
