# Generated by Django 5.2.7 on 2025-10-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_monitoredapi_last_check_monitoredapi_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredapi',
            name='last_check',
        ),
        migrations.RemoveField(
            model_name='monitoredapi',
            name='status',
        ),
    ]
