# Generated by Django 5.2.7 on 2025-10-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_monitoredapi_last_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredapi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
